### ISSUE TITLE
Add hyrax-iiif_av gem

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/britishlibrary#214]
For Audio/Video we need to expose IIIF V3 manifest presentation.  The “prior art” for this work is from [scientist-softserv/utk-hyku](https://github.com/scientist-softserv/utk-hyku) and 	[scientist-softserv/atla_digital_library](https://github.com/scientist-softserv/atla_digitial_library).  And the point person for that is Kirk.

This document provides both a checklist of tasks and documentation on how I reviewed the implications of adding a the [hyrax-iiif_av gem](https://github.com/samvera-labs/hyrax-iiif_av/) to a [Hyku](https://github.com/samvera/hyku) application.  _Note:_ Due to the nature of the task, the checklist should not be considered exhaustive.  It should “get us started” down the path of adding the gem.

- Verify with the client which of their work types should have IIIF audio visual presentation support.  Said another way, what are the types of files that /could/ be attached to each work type.  The recommendation is that we add this behavior to all.  Below is the list (checked items mean they should have them):
  - [x] book
  - [x] dataset
  - [x] book_contribution
  - [x] conference_item
  - [x] generic_work
  - [x] time_based_media
  - [x] thesis_or_dissertation
  - [x] exhibition_item
  - [x] article
  - [x] image
  - [x] report
- [x] Add the gem to the application.
- [x] Run the documented generator for each of the client identified works that should have the extended media support (note you may need to provide the model name).
  - [x] In conversations with Kirk, the generator may not properly work.  As such, you may need to look to prior art for the intended behavior.
- [ ] Review the [Configure IIIF Manifest Fields in Hyrax/Hyku | Wiki.js](https://playbook-staging.notch8.com/en/samvera/hyrax/how_to/configure-iiif-manifest-fields) and adjust accordingly; Kirk is a great wayfinder at this point.

## Tasks Dependent on this Work

- [x] #194 
- [x] #195 
- [ ] #196 

<details>
<summary>Discussion and Additional Working Notes</summary>

This builds on:

<ul class="org-ul">
<li>[IIIF Viewer handles Audio · Issue #194 · scientist-softserv/britishlibrary](https://github.com/scientist-softserv/britishlibrary/issues/194)</li>
<li>[IIIF Viewer handles Video · Issue #195 · scientist-softserv/britishlibrary](https://github.com/scientist-softserv/britishlibrary/issues/195)</li>
</ul>

Reviewing [samvera-labs/hyrax-iiif_av: Hyrax plugin for IIIF Presentation 3.0 audiovisual support](https://github.com/samvera-labs/hyrax-iiif_av).  The  [hyrax-iiif_av.gemspec](https://github.com/samvera-labs/hyrax-iiif_av/blob/888ad531ec08e6c1040d609321972e2147f0c702/hyrax-iiif_av.gemspec#L24) has the following:

```ruby
s.add_dependency "hyrax", "~> 2.9", ">= 2.9.4"
```

If we were to upgrade from Hyrax 2.9.6 for the British Libraries, we could repurpose the [utk-hyku-with-hyrax-3](https://github.com/samvera-labs/hyrax-iiif_av/tree/utk-hyku-with-hyrax-3) branch.

In the [README.md](https://github.com/samvera-labs/hyrax-iiif_av/blob/888ad531ec08e6c1040d609321972e2147f0c702/README.md?plain=1#L7-L11) we have the following notes:

````text
2. Run generator passing your work type:
```
rails g hyrax:iiif_av:add_to_work_type MyWorkType
```
Notice that this generator includes mixins in the work controller and work show presenter.

````

We will need a list of the models.  Below looks for all models that include the `Hyrax::WorkBehavior`; a strong indicator of candidates to add the behavior.

````bash
cd ~/git/britishlibrary/ ; rg "^ +include Hyrax::WorkBehavior" . --files-with-matches
````

````text
./app/models/book.rb
./app/models/book_contribution.rb
./app/models/thesis_or_dissertation.rb
./app/models/time_based_media.rb
./app/models/dataset.rb
./app/models/generic_work.rb
./app/models/conference_item.rb
./app/models/exhibition_item.rb
./app/models/report.rb
./app/models/image.rb
./app/models/article.rb
````

We will also want to assess if those models have any overrides.  In introducing a new gem, we need to know if there are any overrides in `app/models`

````bash
cd ~/git/britishlibrary/ ; rg override ./app/models -i --files-with-matches
````

````text
./app/models/hydra/access_controls/lease_decorator.rb
./app/models/hydra/access_controls/embargo_decorator.rb
./app/models/ability.rb
./app/models/featured_work_list_decorator.rb
./app/models/hyrax/contact_form.rb
````

It doesn’t look like there are issues with the Work models (e.g. those that `include Hyrax::WorkBehavior`).

</details>

### Testing

- [ ] upload a video (mp4) of your choosing as any work type
  - [ ] observe that UV renders and the video can be played
- [ ] upload an audio (wav or mp3) of your choosing as any work type
  - [ ] observe that UV renders and the audio can be played

**Comment by AKFosterDev** [comment]
## Summary
- add Hyrax IIIF AV gem
- switch manifests over from version 2 to version 3 to enable AV
- fix a label bug introduced by switching to IIIF manifest 3
- remove PUL UV
- add UV yarn package
- add `DisplaysContentDecorator` to make the AV gem work for Hyku
- set video bitrate to 1500k
- add specs 

## Related PR
#266 

## Screenshots

### Video example
<img width="610" alt="image" src="https://user-images.githubusercontent.com/19597776/216099792-f97ca812-86b2-49a8-937f-b28173aa175c.png">

### Audio Example
<img width="609" alt="image" src="https://user-images.githubusercontent.com/19597776/216099707-602e031d-75d8-48c9-add3-dff33800b75f.png">

**Comment by AKFosterDev** [comment]
## Sample Files

**MOV File Type**

https://user-images.githubusercontent.com/39319859/217041922-89eddfd7-0048-4894-b819-01e11778d856.MOV

**mp4 File type**

https://user-images.githubusercontent.com/39319859/217043285-b58e836e-450b-48d9-8bf5-c6a00725011a.mp4

**Audio Sample - Could not be uploaded here**
https://assaydepot.slack.com/archives/G030UPFKXLN/p1675704999583239?thread_ts=1675280783.192359&cid=G030UPFKXLN

**Comment by DiemBTran** [comment]
**Needs further review:**

tested with:
- mp3: https://bl.bl-staging.notch8.cloud/concern/generic_works/53ae3a7c-7569-43d3-835c-a27a2ae13c17?locale=en
- mp4: https://bl.bl-staging.notch8.cloud/concern/time_based_medias/17dea313-b64e-477e-943b-6bc31f5ce4e5?locale=en

I paired with Kirk and Deon and we all experienced this same bugged behavior: clicking `View files in viewer` takes you to a new tab with the UV. However, the UV does not display consistently. Rapidly refreshing the UV tab swaps between a few screens:
1. `The page you were looking for doesn't exist.`
2. Blank white screen
3. Blank black screen
4. Fully working UV

<details><summary>The UV tab does not consistently display the UV</summary>

https://user-images.githubusercontent.com/29311858/217111135-f1626a41-7144-467e-a754-efe7f0dafe1e.mp4
</details>

**Comment by kirkkwang** [comment]
@DiemBTran should be fixed by #279, can you check again when you have time?

**Comment by jillpe** [comment]
Tested with:
<details><summary>mp4: </summary>

https://user-images.githubusercontent.com/84697174/219148332-13f60d76-83a8-422c-8175-8594b38f61d9.mp4 </details>

<details><summary>mp3:</summary> (cannot attach in Github thread)</details>

Uploaded an mp4 file as a generic work. Opened in viewer, and was able to play video in the viewer. https://mola.bl-staging.notch8.cloud/concern/generic_works/f8ad69fc-fc1a-40e3-a078-6292866098c3?locale=en

Uploaded an mp3 file as a generic work. Opened in viewer, and was able to play audio in the viewer. https://mola.bl-staging.notch8.cloud/concern/generic_works/08514a36-4c28-4442-bb79-c24fbf5931d7?locale=en

**Comment by j-basford** [comment]
Testing this and am able to add video files, thumbnail has very slowly generated (and a bit squashed!), but waited over 20 mins and video is not yet playing in the UV (it's 1:03 mins long). What is a reasonable timeframe to expect the 15 sec video file to upload, show thumbnail and play in UV? Was wondering how long it took for yours to show in testing, @jillpe and @DiemBTran ? (As could be my internet or remote access through BL network) Thank you!

**Comment by jillpe** [comment]
@j-basford the thumbnails took a while to appear for me also, about 30ish minutes

**Comment by j-basford** [comment]
@jillpe thanks Jill!

**Comment by j-basford** [comment]
Files uploaded successfully and play in viewer and allow download.

Comments: 

1. Can we speed up thumbnail generation (30 mins is quite long? Maybe faster on the prod server?)
2. Need a new thumbnail for audio files that matches the other default ones in the BL colour scheme/'palette'. I think Summer created our current ones.
3. The video of the cat is very squished, is there a way of making it show in the correct resolution?


My tests:
1. https://bl.bl-staging.notch8.cloud/concern/time_based_medias/a0ed4631-f79d-435b-9a4f-64606f884363 (videos)
2. https://bl.bl-staging.notch8.cloud/concern/time_based_medias/e290226f-7b47-4a4d-9ca1-82e3f836725c (audio)

**Comment by cziaarm** [comment]
https://bl.bl-staging.notch8.cloud/concern/time_based_medias/a0ed4631-f79d-435b-9a4f-64606f884363/manifest.json

Two mov files the manifest has 1080x1920 for both but this would appear to be wrong for the _first_ file

**Comment by kirkkwang** [comment]
Hi @j-basford and @cziaarm, we did some quick digging and it looks like because your video is shot with an iPhone, the dimensions are a little wonky.  iPhones have a fixed video ratio such as 1920x1080 (width by height) and even if you flip the phone vertical, it'll stay at that ratio.  What is affected though is a metadata property called `rotation` and it would be set to `90`.  On mine and @laritakr's Android phones, we do not see that issue in this work: https://bl.bl-staging.notch8.cloud/concern/time_based_medias/ed9a5d7f-43e5-476f-aed2-3f482735e209?locale=en

Here is some technical metadata if interested:

```sh
# Jenny's video
$ exiftool IMG_5977__1_.MOV

Source Image Width              : 1920
Source Image Height             : 1080
Rotation                        : 90
```

```sh
# My video
$ exiftool Snapchat-1043596950.mp4

Source Image Width              : 944
Source Image Height             : 1936
Rotation                        : 0
```

```sh
# LaRita's video
$ exiftool VID_20211130_062221873.mp4

Image Width                     : 720
Image Height                    : 1280
Rotation                        : 0
```

Do you forsee ingests of iPhone videos to be in production in some form?  If not, this might not be an issue (unless we find some other edge case).  The fix would need to be handled through Hyrax's `CharacterizeJob` which grabs all the embedded metadata from the file.  If we want to pursue a fix, we feel this would definitely be a different ticket.

The thumbnails are coming in slowly because it is apart of the `CreateDerivativeJob` that also creates the derivative of the video.  Videos do take a lot longer to process than images so that's why there's a noticeable slowdown.  When the video is done generating its derivative, then the thumbnail is also then finished.

**Comment by j-basford** [comment]
Hi @kirkkwang I was just looking at your tests in the bl.bl-staging tenant and saw you have them working, good to know that it behaves with Android! You're right, my video was using an iPhone. We won't have a lot of iPhone content but I could totally see this being used on occasion. I wonder if there is an open issue in the UV community where people are looking into it? I might do a poll of BL colleagues and partners to see if it's something they anticipate putting in, but don't spend any more time on it for now. Thanks!

**Comment by j-basford** [comment]
Re: my request for a default icon for audio files: https://github.com/orgs/scientist-softserv/projects/5/views/1?pane=issue&itemId=21064871

**Comment by kirkkwang** [comment]
Hey @j-basford, I think this might be more of a Hyrax issue rather than a UV, I'd be curious to do a test with your video and I just go in and manually change the width and height to see if it'll just work.  I can take a look at that next time I have this project open and take a peek 🤔

**Comment by jeremyf** [comment]
@NoraRamsey

**Comment by j-basford** [comment]
passes CV
