### ISSUE TITLE
Add "open access" to data feed

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/britishlibrary#331]
# Story

Based on the [given pseudocode](https://github.com/scientist-softserv/britishlibrary/issues/104#issuecomment-1353284758), either the OAI or json record should have "open access" added to the metadata.

# Tasks

- [x] Create OpenAccessService to encapsulate logic with public method `unrestricted_use_files?`
- [x] Add a method `open_access_determination` to work models, based on the [pseudocode linked in the story](https://github.com/scientist-softserv/britishlibrary/issues/104#issuecomment-1353284758)
- [x] Code OpenAccessService logic Plan S funder logic
  - [x] determine how to identify Plan S funders
  - [x] ~~get api key for sherpa service from Rory~~ Not needed until #375
  - [x] add database table & migration to store known plan S funders
  - [x] load database table manually
- [x] Make new issue for api loading tasks https://github.com/scientist-softserv/britishlibrary/issues/375
- [x] Code OpenAccessService logic dealing with embargo date rules
- [x] Determine whether OAI or json feed is the fastest/easiest option for adding the additional rights value
- [x] Add the value to either the OAI feed's metadata based on the results of `open_access_determination`

# Acceptance Criteria

- [ ] a rights value of `Open Access` is available in the OAI feed.

# Testing Instructions

**Testing Scholarly Articles:**
- create a work of type Article, Conference Item, or Generic Work: 
  - Select `peer reviewed`
  - Add a coalition s funder (use `Biotechnology and Biological Sciences Research Council`)
  - check `Does GenericWork include non-restricted use file?` on files tab and upload a file
  - Keep work and file public
  - save the identifier of your new work
- visit /catalog/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=`your identifier`
- [ ] OAI feed should include `Rights Management  info:eu-repo/semantics/openAccess`

**Books:**
- create a work of Book or Book Contribution: 
  - Add a coalition s funder (use `Biotechnology and Biological Sciences Research Council`)
  - Keep work and file public
  - save the identifier of your new work
- visit /catalog/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=`your identifier`
- [ ] OAI feed should include `Rights Management  info:eu-repo/semantics/openAccess`

<details>
<summary>Screenshot</summary>

![Screenshot 2023-04-20 at 2 08 01 PM](https://user-images.githubusercontent.com/17851674/233451422-cffab520-08f3-4b1b-9582-e3ffd51f482a.png)
</details>

# Notes
Feed for json: https://bl.iro.bl.uk/concern/articles/5487ebc4-c860-43f2-b0e6-acc4900ec564?format=json
OAI feed: https://bl.iro.bl.uk//catalog/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=5487ebc4-c860-43f2-b0e6-acc4900ec564
The metadata shown in the oai feed would be `<dc:rights>info:eu-repo/semantics/openAccess</dc:rights>`

The rights value can be added to both OAI and json feeds if it is basically the same amount of work to do both. Otherwise the faster/easier feed should be the one adjusted.

**Comment by laritakr** [comment]
### Specific questions for @cziaarm  

**1) specifics questions on identifying funder:**

I noticed that [ror.org](http://ror.org/) includes Crossref Funder ID under “Other Identifiers”. Is this accurate that we could identify them this way, since the repo already uses the [ror.org](http://ror.org/) api and would just need to be modified to return this metadata? (see https://ror.org/00cwqg982)

Should we be storing anything to identify the funder on the work itself, or would this be something  that would be subject to change so we would need to access at the time we need to make the `open access` determination?

 I'm seeing several places we could possibly be finding info, and am trying to determine the best way. I don't want there to be any issues with using too many api calls as we load the feeds. In addition to ror.org and corssref.org, there is also  https://gitlab.com/crossref/open_funder_registry. 

**2) Clarification of restricted files:**

For **Scholarly articles**, the file can never have been restricted. 

This seems fairly clear, (except that I’ve heard that Hyrax is now adding embargoes for everything, and am not sure which version of hyrax started doing that, and whether it leaves the end date empty or if it makes the end date = the date it was added)

For **Books**, it says the following, and I don’t know what you mean by public_date:

```
- At least one file is present and not restricted and any previous embargo is less than 12 months
   - work.files.present? at least one file.public? && file.embargo_release_date < public_date + 12 months
```

Are you saying that I have to find the original date that the embargo began (which doesn’t seem like a logical meaning of public_date to me)?

**Comment by cziaarm** [comment]
Hi @laritakr,

I'll do 2) first:

`public_date` is not a good name for what I meant here, sorry. The thing that we are testing here is did this thing that has/had an embargo gets/got released from that embargo within twelve months of (what I wrongly called) `public_date`. The simplest interpretation of `public_date` would be the date the file was deposited in the repository and the embargo set.

So in other words yes the date that the embargo began (which in the case of the repo we are assuming is the date of file deposit).

1) We are already (potentially) storing Funder Name, Funder DOI, Funder ISNI, Funder ROR, is the question "why do this when we can just keep the funder ID and access more up to date version of the other things? Which is a good question...

For calculating an answer to the plan S OA question "Does this work have a funder that means it comes under the plan S remit?" it seems that the crossref api will get us the answer more quickly I think. We _should_ have the funder DOI which I _think_ is close enough to the crossref.org api reference for us to make the leap:

http://dx.doi.org/10.13039/501100000268 => https://api.crossref.org/funders/501100000268

then we have the `hierarchy-names` which we can scan for a qualifying national body (https://www.coalition-s.org/plan-s-funders-implementation/) what I can't say is whether there is a machine readable source for that list :/

My colleague has implemented this check for another platform, so I'll ask him what he does... but he's on leave today.

**Comment by laritakr** [comment]
Thanks @cziaarm 

I have coded most of the logic and for now I'm just using `true` for the` coalition S founder` piece as I write specs and figure out where to plug it into one of the feeds. I still have a bit more work, but the logic for this portion will soon become a blocker.

**Comment by wfyson** [comment]
Hi @laritakr - @cziaarm asked me to drop in with a little bit of info on how to determine whether or not we need to worry about an output being Plan S compliant or not, i.e. is it funded by one of the cOAlition S funders?

As Rory mentions, as long as we have the funder DOI we can track this back to a potentially relevant funder. E.g. in the example of http://dx.doi.org/10.13039/501100000268 the "broader" attribute returns http://dx.doi.org/10.13039/100014013 which is the DOI for "UK Research and Innovation", i.e. a Plan S funder. 

So following the chain of funder DOIs up via the "broader" attribute lets us determine which funders are relevant. And stashing those that we've seen on this route allows us to essentially cut back on our Crossref queries as we build a list of which ones ultimately end up at a Plan S funder.

I hope the above makes sense and is what you're after!

**Comment by laritakr** [comment]
@wfyson so you're suggesting we build a list of plan s funders and check that before querying? Do we need to consider funders dropping off of the list?

**Comment by wfyson** [comment]
Hi @laritakr - I've had a chat with @cziaarm now that we're both back and it looks like things got a little confused. As mentioned in Rory's original comment, the hierarchies section of the CrossRef API results (e.g.  https://api.crossref.org/funders/501100000268) skips the process of following the chain of "broader" values up until we find something in Plan S, as it lists all those related funders.

With regards to determining if something is a correct funder or not, Jisc's Sherpa Juliet service maintains a list of relevant funders at https://v2.sherpa.ac.uk/id/funder_group/1063. With an API key registered this can be queried at https://v2.sherpa.ac.uk/cgi/retrieve_by_id?item-type=funder&api-key=<API-KEY>&format=Json&identifier=13 to return the funder IDs of all Plan S funders. Querying Sherpa for each of these in turn then (e.g. https://v2.sherpa.ac.uk/cgi/retrieve_by_id?item-type=funder&api-key=3<API-KEY>&format=Json&identifier=13) returns their DOIs or ROR IDs (as well as also saying they belong to the "Plan S Funders" group). Registering for an API key is a relatively simple process and can be done at https://v2.sherpa.ac.uk/cgi/register

I suspect you wouldn't need to check against this list all the time, but maybe a scheduled job of updating the list to make sure nothing new has been added or one has dropped off would help catch which funders are still relevant?

**Comment by laritakr** [comment]
Just an update to the above comment: 

For now I am adding a CSV to the repo, and processing that to maintain the data. Figuring out the best API calls to get the data right can be handled in ticket #375

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

# Testing Instructions

The following works  should include `Rights Management: info:eu-repo/semantics/openAccess` in their OAI feed
- [x] Article
  - link to work: https://bl.bl-staging.notch8.cloud/concern/articles/ca149eb4-371c-4815-a3a2-fd13b6144417?locale=en
  - link to OAI feed: https://bl.bl-staging.notch8.cloud/catalog/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=ca149eb4-371c-4815-a3a2-fd13b6144417
- [x] Conference Item
  - link to work: https://bl.bl-staging.notch8.cloud/concern/conference_items/b318ffe2-370f-4e06-b6b4-ded56be3b8f9?locale=en
  - link to OAI feed: https://bl.bl-staging.notch8.cloud/catalog/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=b318ffe2-370f-4e06-b6b4-ded56be3b8f9
- [x] Generic Work
  - link to work: https://bl.bl-staging.notch8.cloud/concern/generic_works/54d2fbdf-edf7-4a94-baaa-cfc56c40dbd3?locale=en
  -  link to OAI feed: https://bl.bl-staging.notch8.cloud/catalog/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=54d2fbdf-edf7-4a94-baaa-cfc56c40dbd3
- [x] Book
  - link to work: https://bl.bl-staging.notch8.cloud/concern/books/49a01257-55cf-46f6-b8a8-9c22860db5ef?locale=en
  -  link to OAI feed: https://bl.bl-staging.notch8.cloud/catalog/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=49a01257-55cf-46f6-b8a8-9c22860db5ef
- [x] Book Contribution
  - link to work: https://bl.bl-staging.notch8.cloud/concern/book_contributions/fc43edb8-1016-46ac-9779-4dff286ff3ea?locale=en
  -  link to OAI feed: https://bl.bl-staging.notch8.cloud/catalog/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=fc43edb8-1016-46ac-9779-4dff286ff3ea

<details><summary>Specified works with the relevant metadata will have "Rights Management: info:eu-repo/semantics/openAccess" in their OAI feed</summary>

![another conference item Conference Item  b318ffe2-370f-4e06-b6b4-ded56be3b8f9  BL Staging 2023-04-26 at 4 27 08 PM](https://user-images.githubusercontent.com/29311858/234724379-be99cd94-973a-4411-a40e-3ecedaa317f8.jpg)
![another conference item Conference Item  b318ffe2-370f-4e06-b6b4-ded56be3b8f9  BL Staging 2023-04-26 at 4 28 28 PM](https://user-images.githubusercontent.com/29311858/234724412-6b3ad0af-12b3-41da-9aa1-948d1216245c.jpg)
![another conference item Conference Item  b318ffe2-370f-4e06-b6b4-ded56be3b8f9  BL Staging 2023-04-26 at 4 29 54 PM](https://user-images.githubusercontent.com/29311858/234724432-0e83b7a6-ca47-44a6-acbf-37103da220c4.jpg)
![OAI 2 0 Request Results 2023-04-26 at 4 30 18 PM](https://user-images.githubusercontent.com/29311858/234724438-7f3c5271-907c-4216-b2c7-4ebc2a06e9e9.jpg)


</details>

**Comment by laritakr** [comment]
Requires run of rake task upon deploy to production to load PlanSFunder table.

**Comment by grahamjevon** [comment]
Before passing this through QA I need to flag one aspect of the testing instructions that does not appear to be working as expected. The testing instructions at the top of this thread state:

![Image](https://user-images.githubusercontent.com/51366817/236222801-7b940ca9-1af4-4a1f-93f2-2e4009128dd0.png)

However, I have uploaded [a work without this box checked](https://bl.bl-staging.notch8.cloud/concern/conference_items/a50d1a44-4524-482a-9842-5920cde67800?locale=en), and the rights management info still appears in the OAI feed.

I notice in those original testing instructions that this box did not need to be checked for books or book contributions. But it states that it is required for articles, conference items, and generic works.

![Image](https://user-images.githubusercontent.com/51366817/236225414-d7d5db01-da04-4949-bc00-5bbd06263dc8.png)


![Image](https://user-images.githubusercontent.com/51366817/236223588-d35ee396-e3b9-4a46-ab88-7034136be815.png)

I don't know if checking this box is actually necessary (maybe this has been intentionally removed from the logic in the intervening discussions?), but as it was in the original testing instructions, I wanted to flag this before passing it through QA because it seems to function as expected in every other respect.

**Comment by laritakr** [comment]
Thanks for the heads-up. I will move it back to rework. The box should only appear on the worktypes where it is needed.

**Comment by DeonFranklin** [comment]
- [ ] Create a work of type Article, Conference Item, or Generic Work: 
 - [ ] Select `peer reviewed`
 - [ ] Add a coalition s funder (use `Biotechnology and Biological Sciences Research Council`)
- [ ] Check `Does GenericWork include non-restricted use file?` on files tab and upload a file
- [ ] Keep work and file public
- [ ] Save the identifier of your new work
- visit /catalog/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=`your identifier`
- [ ] OAI feed should include `Rights Management  info:eu-repo/semantics/openAccess`

![image](https://github.com/scientist-softserv/britishlibrary/assets/95306716/eee3335e-1afa-4e8b-a75c-1ba774d57a6c)

**Books:**
- [ ] Create a work of Book or Book Contribution: 
- [ ] Add a coalition s funder (use `Biotechnology and Biological Sciences Research Council`)
- [ ] Keep work and file public
- [ ] Save the identifier of your new work
- visit /catalog/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=`your identifier`
- [ ] OAI feed should include `Rights Management  info:eu-repo/semantics/openAccess`

![image](https://github.com/scientist-softserv/britishlibrary/assets/95306716/46929e3d-4065-43e2-9ddb-0fd6d1680e55)

**Comment by grahamjevon** [comment]
Passes BL QA
