### ISSUE TITLE
Automate maintenance of cOAlition S funders table (PlanSFunder)

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/britishlibrary#375]
# Story

PlanSFunder database table will be created and loaded in https://github.com/scientist-softserv/britishlibrary/issues/331
Periodic maintenance (somewhere between 1x per week and 1x per month) is needed to keep funder information up to date.

# Tasks

- [x] Use array of DOI's returned from `MaintainPlanSFunders.call` to find and reindex all affected works. 
    - [x] If PlanSFunder is loaded prior to the implementation of the reindex of works task above, the reindex step should be handled or existing works will not show as open access in the OAI feed.
- [x] Add api key to secrets and set up api call to Sherpa service if desired (see notes below)
       (currently handled via csv in `lib/data` and this may be an adequate method)
- [x] Determine schedule for maintaining funder data [_(once per month)_](https://assaydepot.slack.com/archives/C0313NK2LJ0/p1682094729097529)
- [ ] ~Determine preferred method of maintaining table data (rake task, periodic job, UI option, etc) _(monthly cron job is recommended)_~
- [ ] ~Automate preferred maintenance method.~

# Testing Instructions and Sample Files

This ticket can only be tested by running the scripts via the rails console or rake task.

Due to questions on the quality of the API data, the service is not yet automated. However it can be called on a rails console: `SherpaApiFunderService.process_funders(export: false, update: false)`
- with no parameters: outputs an array of hashes of funder info
- `export: true` writes funder info to a tmp file
- `export: true, update: true` immediately uses the above tmp file to maintain PlanSFunder (via `MaintainPlanSFunders.call` and submit of the reindexing job)

Alternately, `MaintainPlanSFunders` with no parameters uses [the csv in lib/data](https://github.com/scientist-softserv/britishlibrary/blob/main/lib/data/plan_s_funders.csv), and can be triggered [using rake tasks](https://github.com/scientist-softserv/britishlibrary/blob/main/lib/tasks/funders.rake) after updating the csv data manually.

# Screenshots / Video

<details>
<summary></summary>

### Output from call in rails console:
**Reindexing job submitted showing DOIs being reindexed, and array of all funders found via API calls :**
![Screenshot 2023-04-26 at 7 42 07 PM](https://user-images.githubusercontent.com/17851674/234725410-4e911c70-8925-45c5-a0fc-098870dac38b.png)

**Results of reindexing job over development environment:**
![Screenshot 2023-04-26 at 7 42 18 PM](https://user-images.githubusercontent.com/17851674/234725482-43878142-2d95-43c8-88cb-85c08d31782a.png)

</details>

# Notes

- Processing the data:
    - Use BL's API key to access the feed for [Sherpa site](https://v2.sherpa.ac.uk/id/funder_group/1063)'s list of funders. 
        - https://v2.sherpa.ac.uk/cgi/retrieve_by_id?item-type=funder_group&api-key=SUPER-SPECIAL-API-KEY&format=Json&identifier=1063
    - Retrieve each item under `funders`, using its id
        - https://v2.sherpa.ac.uk/cgi/retrieve_by_id?item-type=funder&api-key=SUPER-SPECIAL-API-KEY&format=Json&identifier=xxx 
        - find the doi from `funder_metadata: identifiers: identifier` where `funder_metadata:identifiers:type` = `fundref` 
    - if there is no fundref section, do we need to use type = `ror` to access the crossref api for the doi?? 
- See [#331](https://github.com/scientist-softserv/britishlibrary/issues/331#issuecomment-1516801850) for details of difficulties with API use which would need to be resolved if updating via API. 
- My thought is to use the API to write a CSV, and continue to use existing service to maintain it. But we may instead choose to manually maintain the CSV in the repo to simplify the process.
- to prevent issues between DOIs beginning with `http://doi.org` and DOI's beginning with `https://dx.doi.org`, a regex should be used to store only the consistent portion of the DOI in the PlanSFunder table. `cleaned_doi = doi.match(%r{https?://.*doi\.org/(.+)})[1]`

**Comment by laritakr** [comment]
depends on https://github.com/scientist-softserv/britishlibrary/issues/331

**Comment by jillpe** [comment]
@j-basford @grahamjevon @NoraRamsey For the Plan S funders, how often do you want that list updated? (i.e. once a month, twice a year, etc.)

**Comment by j-basford** [comment]
> @j-basford @grahamjevon @NoraRamsey For the Plan S funders, how often do you want that list updated? (i.e. once a month, twice a year, etc.)

monthly is fine! thanks all :)

**Comment by laritakr** [comment]
Automatic maintenance is blocked pending decision regarding API data quality... [see slack thread](https://assaydepot.slack.com/archives/G030UPFBT2S/p1682537557186119) for details.

**Comment by laritakr** [comment]
Considered complete per @cziaarm - [see discussion on slack](https://assaydepot.slack.com/archives/G030UPFBT2S/p1682537557186119)
