### ISSUE TITLE
[M] Add Metadata to display in UV

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/britishlibrary#75]
# Summary

Is it possible to pull at least minimal metadata through to the metadata panel in the viewer itself? Currently nothing is displayed. If not possible, please could you explain? e/g what needs to happen to fix it?

Order of metadata should be considered. Prefer Title, Creators, and license higher up on the list. 
- [Helpful place to start when looking at sorting the metadata](https://assaydepot.slack.com/archives/G031E2P1RJM/p1668632867008359)

References #167 

# Task

- [ ] Determine fields to show in-viewer
- [ ] Determine order of fields to show in-viewer
- [ ] Implement showing fields in desired order

# Acceptance Criteria

- [ ] Add what metadata should show
- [ ] Add a mockup of where the metadata should display

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by DiemBTran** [comment]
Rory Nov 2021 - 

---

Had a look at this with reference to Kings's fund as promised, here's what I found: 

The iiif_manifest gem will render a metadata block if it finds `manifest_metadata` defined by the `IiifManifestPresenter`. It will include the fields as per the the config item `Hyrax.config.iiif_metadata_fields`. Easy, no? No!


The definition of manifest_metdata in hyrax 2.x is broken 

https://github.com/samvera/hyrax/blob/2.x-stable/app/presenters/hyrax/iiif_manifest_presenter.rb#L74 

The above line of code attempts to reference the attribute values with `self[field_name]` and gets nowt back so the metadata var remains `[]` and no metadata is added to manifest. This needs to be overridden so the above code instead uses `self.send(field_name)`

I've done this for the King's fund using the same prepend I used to add the search URI. I'm going to leave it to @orangewolf and @alishaevn to suggest how they would prefer the `IiifManifestPresenter.manifest_metadata` method to be overridden for the BL (happy to put an MR together once I have your vote on where to do this)

Lastly the above approach works for a single tenant and as long as BL are happy to use the same `iiif_metadata_fields` or the same rule (e.g. `required_fields` == `iiif_metadata_fields`) across all the repos then the above will work fine. If we need this to be a per tenant or per work config item there's a little more to do. Input from @SaraGould and @jbasford on that point probably a good idea.

**Comment by DiemBTran** [comment]
Rory Nov 2021 - 

---

or an alternate solution which might be less invasive and would not require anything to be overridden, would be to use the solr field names is `Hyrax.config.iiif_metadata_fields` so `title_tesim` `doi_ssi` etc etc... feels a bit like a slapdash workaround to me, but I could be being fussy?

**Comment by jillpe** [comment]
As of client meeting 11/15:
- All metadata shown on the works page can be added to the UV

**Comment by jillpe** [comment]
There are some fields that need custom work to display appropriately (i.e. creator)

**Comment by jillpe** [comment]
Need to determine which fields to expose

**Comment by jillpe** [comment]
https://github.com/scientist-softserv/iiif_print/blob/main/lib/iiif_print/configuration.rb#L55-L81 This is what should be being revealed by default

**Comment by jillpe** [comment]
closed - take care of with installation of iiif_print gem
